apiVersion: v1
kind: Service
metadata:
  name: frontend 
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - name: my-https-port
    port: 443
    targetPort: 443
  - name: my-http-port
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-v1-lb-svc
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 80
  - name: ssl
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: bck-container 
          image: us-central1-docker.pkg.dev/watchmen-monitoring/repo/frontend:latest
          resources:
            limits:
              cpu: "4"
              memory: "500Mi"
            requests:
              cpu: "2"
              memory: "300Mi"
          ports:
          - containerPort: 9000