name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:  
      IMAGE_NAME: frontend
      PROJECT_ID: watchmen-monitoring
      REPOSITORY: repo
      GKE_LOCATION: us-central1 
      GKE_CLUSTER: cluster-1 
    steps:
    - name: Checkout   
      uses: actions/checkout@v2     
 
    # - uses: google-github-actions/setup-gcloud@v2
    - uses: google-github-actions/auth@v2 
      with:   
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker Client
      run: |-  
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker ${GKE_LOCATION}-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.21
      run: |-
        docker build -t $IMAGE_NAME:latest .
        docker tag $IMAGE_NAME:latest ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/$IMAGE_NAME:latest
        docker push ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/$IMAGE_NAME:latest
        
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: '${{ env.GKE_CLUSTER }}'
        location: '${{ env.GKE_LOCATION }}'
        project_id: '${{ env.PROJECT_ID }}'

    - name: Apply deployment if not exists
      run: |-
        kubectl apply -f deployment.yaml
