name: Build and Push Python Image to Google Cloud Platform
# on:
#   push:
#     branches: [ main ]
on:
  workflow_dispatch:
    inputs:
      imagename:
        description: "Name of the Docker image"
        required: true

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:  
      PROJECT_ID: monitoring-442416
      REPOSITORY: repo
      GKE_LOCATION: us-central1
    steps: 
    - name: Checkout   
      uses: actions/checkout@v2     
 
    # - uses: google-github-actions/setup-gcloud@v2
    - uses: google-github-actions/auth@v2 
      with:   
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker Client
      run: |-  
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker ${GKE_LOCATION}-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.21
      run: |-
        docker build -t ${{ github.event.inputs.imagename }}:latest .
        # docker compose -f docker-compose.yaml build
        docker tag $IMAGE_NAME:latest ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${{ github.event.inputs.imagename }}:latest
        # docker push us-central1-docker.pkg.dev/backend-440112/repo/$IMAGE_NAME:latest
        docker push ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${{ github.event.inputs.imagename }}:latest

    
