name: Build and Push Front End to Google Cloud Platform
# on:
#   push:
#     branches: [ main ]
on:
  push:
    branches: [ master ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:  
      PROJECT_ID: monitoring-442416
      REPOSITORY: repo
      IMAGE: ttfrontend
      GKE_LOCATION: us-central1
    steps: 
    - name: Checkout   
      uses: actions/checkout@v2     
 
    # - uses: google-github-actions/setup-gcloud@v2
    - uses: google-github-actions/auth@v2 
      with:   
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker Client
      run: |-  
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker ${GKE_LOCATION}-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.21
      run: |-
        docker build -t ${IMAGE}:latest .
        # docker compose -f docker-compose.yaml build
        docker tag ${IMAGE}:latest ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest
        # docker push us-central1-docker.pkg.dev/backend-440112/repo/$IMAGE_NAME:latest
        docker push ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest
        
    - name: Get Latest Tag
      id: get_latest_tag
      run: |
          # Get the latest tag or set a default version if no tags exist
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Bump Version
      id: bump_version
      run: |
          # Extract version numbers from the latest tag
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag#v }}"
          patch=$((patch + 1)) # Increment patch version
          new_version="v$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Create New Tag
      run: |
          # Create a new tag with the incremented version
          git tag "${{ env.new_version }}"
          git push origin "${{ env.new_version }}"
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    
