name: Build and Push Front End to Google Cloud Platform
# on:
#   push:
#     branches: [ main ]
on:
  push:
    branches: [ master ]
permissions:
  contents: write
jobs: 
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:  
      PROJECT_ID: monitoring-442416
      REPOSITORY: repo
      IMAGE: mtfrontend
      GKE_LOCATION: us-central1
    steps: 
    - name: Checkout   
      uses: actions/checkout@v2     
 
    # - uses: google-github-actions/setup-gcloud@v2
    - uses: google-github-actions/auth@v2 
      with:   
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure Docker Client
      run: |-  
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker ${GKE_LOCATION}-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.21
      run: |-
        docker build -t ${IMAGE}:latest .
        # docker compose -f docker-compose.yaml build
        docker tag ${IMAGE}:latest ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest
        # docker push us-central1-docker.pkg.dev/backend-440112/repo/$IMAGE_NAME:latest
        docker push ${GKE_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest
        
    - name: Read Version from package.json
      id: get_version
      run: |
          version=$(jq -r '.version' package.json)
          echo "VERSION=$version" >> $GITHUB_ENV

    - name: Create and Push Tag
      run: |
          git tag "v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    
